name: Publish

on:
  [push]
#    tags:
#      - v*

env:
  DOCKERHUB_URL: ghcr.io/nexys-system/go-min-web-server/go-min-web-server

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      #- name: docker pull
      #  run: docker pull $DOCKERHUB_URL
      - name: create docker container
        run: docker build --build-arg GIT_SHA=$GITHUB_SHA --build-arg GIT_VERSION=${GITHUB_REF##*/} --tag $DOCKERHUB_URL:latest --tag $DOCKERHUB_URL:${GITHUB_REF##*/} .
      - name: Push
        run: docker push --all-tags $DOCKERHUB_URL
